name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, alerts-service, api-gateway, notifications-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew -p ${{ matrix.service }} build -x test
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.service }}
          path: ${{ matrix.service }}/build/libs/*.jar
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: soydz/fg360-${{ matrix.service }}
          tags: latest
          registry: docker.io
          dockerfile: ${{ matrix.service }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
